import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"

import { LanguageProvider } from "@/lib/LanguageContext"
import { ThemeProvider } from "@/lib/ThemeContext"
import { TripProvider } from "@/lib/trip-context"
import { SplashScreen } from "@/components/ui/splash-screen"
import dynamic from "next/dynamic"

// Dynamic import for ChatWidget - reduces initial bundle size
const ChatWidget = dynamic(() => import("@/components/chat-widget"), {
  ssr: false,
  loading: () => null // No loading state needed for chat widget
})

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  themeColor: "#fafaf9",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export const metadata: Metadata = {
  title: "Tabidachi - AI Travel Planner",
  description: "Generated by Ryan",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Tabidachi",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <LanguageProvider>
            <TripProvider>
              <SplashScreen />
              {children}
              <ChatWidget />
            </TripProvider>
          </LanguageProvider>
        </ThemeProvider>
        <Toaster position="bottom-center" richColors />
      </body>
    </html>
  );
}
