import json
import os
from pathlib import Path

def build_static_db():
    base_dir = Path(__file__).parent.parent / "backend" / "data"
    output_file = base_dir / "static_db.py"
    
    print(f"Build Static DB from {base_dir}")
    
    # 1. Load Brands
    brands_db = {}
    brands_path = base_dir / "brands.json"
    if brands_path.exists():
        with open(brands_path, "r", encoding="utf-8") as f:
            brands_db = json.load(f)
            print(f"Loaded brands: {len(brands_db)} categories")
            
    # 2. Load Landmarks (Base + Countries)
    landmarks_data = {}
    
    # Base landmarks.json
    landmarks_path = base_dir / "landmarks.json"
    if landmarks_path.exists():
        with open(landmarks_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            # Filter
            valid = {k: v for k, v in data.items() if isinstance(v, dict) and not k.startswith("_")}
            landmarks_data.update(valid)
            print(f"Loaded base landmarks: {len(valid)}")
            
    # Country folders
    countries_dir = base_dir / "countries"
    if countries_dir.exists():
        for country_path in countries_dir.iterdir():
            if country_path.is_dir():
                for json_file in country_path.glob("*.json"):
                    with open(json_file, "r", encoding="utf-8") as f:
                        data = json.load(f)
                        valid = {k: v for k, v in data.items() if isinstance(v, dict) and not k.startswith("_")}
                        landmarks_data.update(valid)
                        print(f"Loaded {country_path.name}/{json_file.name}: {len(valid)}")
                        
    # 3. Write to Python File
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/build_static_db.py\n")
        f.write("# DO NOT EDIT MANUALLY\n\n")
        
        f.write(f"BRANDS_DB = {json.dumps(brands_db, ensure_ascii=False, indent=4)}\n\n")
        f.write(f"EXTERNAL_LANDMARKS = {json.dumps(landmarks_data, ensure_ascii=False, indent=4)}\n")
        
    print(f"✅ Static DB generated at {output_file}")

if __name__ == "__main__":
    build_static_db()
