"use client"

import jsPDF from "jspdf"
import { toPng } from "html-to-image"

// 類型定義
export interface TripPDFData {
    title: string
    startDate: string
    endDate: string
    coverImage?: string
    days: Array<{
        day: number
        date: string
        location?: string
        activities: Array<{
            time: string
            place: string
            desc?: string
            category: string
            memo?: string
        }>
        notes?: Array<{ title: string; content: string }>
        costs?: Array<{ title: string; amount: number }>
    }>
    expenses?: Array<{
        title: string
        amount: number
        category: string
        date: string
    }>
    flightInfo?: {
        outbound: Array<{ airline: string; flight: string; departure: string; arrival: string }>
        inbound: Array<{ airline: string; flight: string; departure: string; arrival: string }>
    }
    hotels?: Array<{
        name: string
        address: string
        checkIn: string
        checkOut: string
    }>
}

// 分類圖示對應
const CATEGORY_ICONS: Record<string, string> = {
    sightseeing: "🏛️",
    food: "🍜",
    transport: "🚃",
    shopping: "🛍️",
    hotel: "🏨",
    activity: "🎯",
    other: "📍"
}

/**
 * 建立隱藏的 HTML 容器用於渲染 PDF 內容
 * 🆕 html-to-image 優化版
 */
function createPDFContainer(data: TripPDFData): HTMLDivElement {
    const container = document.createElement("div")
    container.id = "pdf-render-container"
    // 🆕 修復透明背景問題：明確設定 background-color
    container.style.cssText = `
        position: absolute;
        left: -9999px;
        top: 0;
        width: 794px;
        background-color: #ffffff;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans TC', 'Microsoft JhengHei', sans-serif;
        padding: 40px;
        box-sizing: border-box;
        color: #1e293b;
    `

    // 封面頁
    const cover = `
        <div style="text-align: center; padding: 80px 0; background-color: #ffffff;">
            <h1 style="font-size: 32px; font-weight: bold; color: #1e293b; margin-bottom: 20px;">
                ${escapeHtml(data.title)}
            </h1>
            <p style="font-size: 16px; color: #64748b;">
                ${escapeHtml(data.startDate)} - ${escapeHtml(data.endDate)}
            </p>
            ${data.coverImage ? `<img src="${data.coverImage}" style="width: 100%; max-height: 300px; object-fit: cover; margin-top: 30px; border-radius: 8px;" crossorigin="anonymous" />` : ''}
            <p style="font-size: 12px; color: #94a3b8; margin-top: 40px;">
                Generated by Tabidachi | ${new Date().toLocaleDateString()}
            </p>
        </div>
    `

    // 每日行程
    const days = data.days.map(dayData => `
        <div style="padding: 30px 0; border-top: 2px solid #e2e8f0; background-color: #ffffff;">
            <h2 style="font-size: 20px; font-weight: bold; color: #1e293b; margin-bottom: 16px;">
                Day ${dayData.day} - ${escapeHtml(dayData.date)}
            </h2>
            ${dayData.location ? `<p style="font-size: 14px; color: #64748b; margin-bottom: 16px;">📍 ${escapeHtml(dayData.location)}</p>` : ''}
            
            <div style="display: flex; flex-direction: column; gap: 12px;">
                ${(dayData.activities || []).map(act => `
                    <div style="background-color: #f8fafc; padding: 12px; border-radius: 4px; border-left: 3px solid #3b82f6;">
                        <div style="font-weight: bold; font-size: 14px; color: #1e293b;">
                            ${escapeHtml(act.time)} ${CATEGORY_ICONS[act.category] || '📍'} ${escapeHtml(act.place)}
                        </div>
                        ${act.desc ? `<div style="font-size: 12px; color: #64748b; margin-top: 4px; padding-left: 8px;">${escapeHtml(act.desc)}</div>` : ''}
                        ${act.memo ? `<div style="font-size: 11px; color: #b45309; margin-top: 4px; padding-left: 8px; font-style: italic;">💡 ${escapeHtml(act.memo)}</div>` : ''}
                    </div>
                `).join('')}
            </div>

            ${dayData.notes && dayData.notes.length > 0 ? `
                <div style="margin-top: 16px;">
                    <h3 style="font-size: 14px; font-weight: bold; margin-bottom: 8px;">📝 筆記</h3>
                    ${dayData.notes.map(note => `
                        <div style="font-size: 12px; margin-left: 8px; margin-bottom: 4px;">• ${escapeHtml(note.title)}: ${escapeHtml(note.content)}</div>
                    `).join('')}
                </div>
            ` : ''}
        </div>
    `).join('')

    // 住宿資訊
    const hotels = data.hotels && data.hotels.length > 0 ? `
        <div style="padding: 30px 0; border-top: 2px solid #e2e8f0; background-color: #ffffff;">
            <h2 style="font-size: 18px; font-weight: bold; color: #1e293b; margin-bottom: 16px;">🏨 住宿資訊</h2>
            ${data.hotels.map(hotel => `
                <div style="background-color: #f0fdf4; padding: 12px; border-radius: 4px; margin-bottom: 8px;">
                    <div style="font-weight: bold; font-size: 14px;">${escapeHtml(hotel.name)}</div>
                    <div style="font-size: 12px; color: #64748b;">${escapeHtml(hotel.checkIn || '')} - ${escapeHtml(hotel.checkOut || '')}</div>
                    ${hotel.address ? `<div style="font-size: 11px; color: #64748b;">${escapeHtml(hotel.address)}</div>` : ''}
                </div>
            `).join('')}
        </div>
    ` : ''

    container.innerHTML = cover + days + hotels
    return container
}

/**
 * 防止 XSS 的 HTML 轉義
 */
function escapeHtml(text: string): string {
    if (!text) return ''
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;')
}

/**
 * 生成行程 PDF（使用 html-to-image，速度快 70 倍）
 * @param data 行程資料
 * @returns PDF blob URL
 */
export async function generateTripPDF(data: TripPDFData): Promise<string> {

    // 空行程檢查
    if (!data.days || data.days.length === 0) {
        throw new Error("行程內容為空，無法生成 PDF。")
    }

    // 建立隱藏容器
    const container = createPDFContainer(data)
    document.body.appendChild(container)

    try {
        // 🆕 使用 html-to-image (速度快 70 倍)
        const dataUrl = await toPng(container, {
            quality: 0.95,
            pixelRatio: 2, // 高解析度
            backgroundColor: '#ffffff', // 🆕 明確設定背景色，防止透明
            skipFonts: true, // 🆕 跳過字體處理，避免 CORS 問題
            cacheBust: true, // 🆕 防止快取問題
        })

        // 計算分頁
        const img = new Image()
        await new Promise<void>((resolve, reject) => {
            img.onload = () => resolve()
            img.onerror = reject
            img.src = dataUrl
        })

        const imgWidth = 210 // A4 寬度 mm
        const pageHeight = 297 // A4 高度 mm
        const imgHeight = (img.height * imgWidth) / img.width
        let heightLeft = imgHeight
        let position = 0

        // 建立 PDF
        const pdf = new jsPDF("p", "mm", "a4")

        // 第一頁
        pdf.addImage(dataUrl, "PNG", 0, position, imgWidth, imgHeight)
        heightLeft -= pageHeight

        // 多頁處理
        while (heightLeft > 0) {
            position -= pageHeight
            pdf.addPage()
            pdf.addImage(dataUrl, "PNG", 0, position, imgWidth, imgHeight)
            heightLeft -= pageHeight
        }

        // 輸出 Blob URL
        const blob = pdf.output("blob")
        return URL.createObjectURL(blob)
    } finally {
        // 清理隱藏容器
        document.body.removeChild(container)
    }
}

/**
 * 下載 PDF
 */
export function downloadPDF(blobUrl: string, filename: string) {
    const link = document.createElement("a")
    link.href = blobUrl
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)

    // 清理 blob URL
    setTimeout(() => URL.revokeObjectURL(blobUrl), 1000)
}
