"use client"

import jsPDF from "jspdf"
import html2canvas from "html2canvas"

// 類型定義
export interface TripPDFData {
    title: string
    startDate: string
    endDate: string
    coverImage?: string
    days: Array<{
        day: number
        date: string
        location?: string
        activities: Array<{
            time: string
            place: string
            desc?: string
            category: string
            memo?: string
        }>
        notes?: Array<{ title: string; content: string }>
        costs?: Array<{ title: string; amount: number }>
    }>
    expenses?: Array<{
        title: string
        amount: number
        category: string
        date: string
    }>
    flightInfo?: {
        outbound: Array<{ airline: string; flight: string; departure: string; arrival: string }>
        inbound: Array<{ airline: string; flight: string; departure: string; arrival: string }>
    }
    hotels?: Array<{
        name: string
        address: string
        checkIn: string
        checkOut: string
    }>
}

// 分類圖示對應
const CATEGORY_ICONS: Record<string, string> = {
    sightseeing: "🏛️",
    food: "🍜",
    transport: "🚃",
    shopping: "🛍️",
    hotel: "🏨",
    activity: "🎯",
    other: "📍"
}

/**
 * 建立隱藏的 HTML 容器用於渲染 PDF 內容
 * 使用 html2canvas 截圖方式支援中文
 */
function createPDFContainer(data: TripPDFData): HTMLDivElement {
    const container = document.createElement("div")
    container.id = "pdf-render-container"
    container.style.cssText = `
        position: absolute;
        left: -9999px;
        top: 0;
        width: 210mm;
        background: white;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans TC', 'Microsoft JhengHei', sans-serif;
        padding: 15mm;
        box-sizing: border-box;
    `

    // 封面頁
    const cover = `
        <div style="text-align: center; padding: 40mm 0;">
            <h1 style="font-size: 28pt; font-weight: bold; color: #1e293b; margin-bottom: 10mm;">
                ${data.title}
            </h1>
            <p style="font-size: 14pt; color: #64748b;">
                ${data.startDate} - ${data.endDate}
            </p>
            ${data.coverImage ? `<img src="${data.coverImage}" style="width: 100%; max-height: 80mm; object-fit: cover; margin-top: 15mm; border-radius: 8px;" crossorigin="anonymous" />` : ''}
            <p style="font-size: 10pt; color: #94a3b8; position: absolute; bottom: 20mm; left: 0; right: 0;">
                Generated by Tabidachi | ${new Date().toLocaleDateString()}
            </p>
        </div>
    `

    // 每日行程
    const days = data.days.map(dayData => `
        <div style="page-break-before: always; padding-top: 10mm;">
            <h2 style="font-size: 18pt; font-weight: bold; color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 5mm; margin-bottom: 8mm;">
                Day ${dayData.day} - ${dayData.date}
            </h2>
            ${dayData.location ? `<p style="font-size: 12pt; color: #64748b; margin-bottom: 8mm;">📍 ${dayData.location}</p>` : ''}
            
            <div style="display: flex; flex-direction: column; gap: 4mm;">
                ${dayData.activities.map(act => `
                    <div style="background: #f8fafc; padding: 4mm; border-radius: 4px; border-left: 3px solid #3b82f6;">
                        <div style="font-weight: bold; font-size: 11pt; color: #1e293b;">
                            ${act.time} ${CATEGORY_ICONS[act.category] || '📍'} ${act.place}
                        </div>
                        ${act.desc ? `<div style="font-size: 10pt; color: #64748b; margin-top: 2mm; padding-left: 3mm;">${act.desc}</div>` : ''}
                        ${act.memo ? `<div style="font-size: 9pt; color: #b45309; margin-top: 2mm; padding-left: 3mm; font-style: italic;">💡 ${act.memo}</div>` : ''}
                    </div>
                `).join('')}
            </div>

            ${dayData.notes && dayData.notes.length > 0 ? `
                <div style="margin-top: 8mm;">
                    <h3 style="font-size: 12pt; font-weight: bold; margin-bottom: 4mm;">📝 筆記</h3>
                    ${dayData.notes.map(note => `
                        <div style="font-size: 10pt; margin-left: 3mm; margin-bottom: 2mm;">• ${note.title}: ${note.content}</div>
                    `).join('')}
                </div>
            ` : ''}
        </div>
    `).join('')

    // 住宿資訊
    const hotels = data.hotels && data.hotels.length > 0 ? `
        <div style="page-break-before: always; padding-top: 10mm;">
            <h2 style="font-size: 16pt; font-weight: bold; color: #1e293b; margin-bottom: 8mm;">🏨 住宿資訊</h2>
            ${data.hotels.map(hotel => `
                <div style="background: #f0fdf4; padding: 4mm; border-radius: 4px; margin-bottom: 4mm;">
                    <div style="font-weight: bold; font-size: 11pt;">${hotel.name}</div>
                    <div style="font-size: 10pt; color: #64748b;">${hotel.checkIn || ''} - ${hotel.checkOut || ''}</div>
                    ${hotel.address ? `<div style="font-size: 9pt; color: #64748b;">${hotel.address}</div>` : ''}
                </div>
            `).join('')}
        </div>
    ` : ''

    container.innerHTML = cover + days + hotels
    return container
}

/**
 * 生成行程 PDF（使用 html2canvas 支援中文）
 * @param data 行程資料
 * @returns PDF blob URL
 */
export async function generateTripPDF(data: TripPDFData): Promise<string> {
    // 建立隱藏容器
    const container = createPDFContainer(data)
    document.body.appendChild(container)

    try {
        // 使用 html2canvas 截圖
        const canvas = await html2canvas(container, {
            scale: 2, // 高解析度
            useCORS: true,
            allowTaint: true,
            backgroundColor: "#ffffff",
            logging: false
        })

        // 計算分頁
        const imgWidth = 210 // A4 寬度 mm
        const pageHeight = 297 // A4 高度 mm
        const imgHeight = (canvas.height * imgWidth) / canvas.width
        let heightLeft = imgHeight
        let position = 0

        // 建立 PDF
        const pdf = new jsPDF("p", "mm", "a4")
        const imgData = canvas.toDataURL("image/jpeg", 0.95)

        // 第一頁
        pdf.addImage(imgData, "JPEG", 0, position, imgWidth, imgHeight)
        heightLeft -= pageHeight

        // 多頁處理
        while (heightLeft > 0) {
            position -= pageHeight
            pdf.addPage()
            pdf.addImage(imgData, "JPEG", 0, position, imgWidth, imgHeight)
            heightLeft -= pageHeight
        }

        // 輸出 Blob URL
        const blob = pdf.output("blob")
        return URL.createObjectURL(blob)
    } finally {
        // 清理隱藏容器
        document.body.removeChild(container)
    }
}

/**
 * 下載 PDF
 */
export function downloadPDF(blobUrl: string, filename: string) {
    const link = document.createElement("a")
    link.href = blobUrl
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)

    // 清理 blob URL
    setTimeout(() => URL.revokeObjectURL(blobUrl), 1000)
}
