"use client"

import jsPDF from "jspdf"
import html2canvas from "html2canvas-pro"

// 類型定義
export interface TripPDFData {
    title: string
    startDate: string
    endDate: string
    coverImage?: string
    days: Array<{
        day: number
        date: string
        location?: string
        activities: Array<{
            time: string
            place: string
            desc?: string
            category: string
            memo?: string
        }>
        notes?: Array<{ title: string; content: string }>
        costs?: Array<{ title: string; amount: number }>
    }>
    expenses?: Array<{
        title: string
        amount: number
        category: string
        date: string
    }>
    flightInfo?: {
        outbound: Array<{ airline: string; flight: string; departure: string; arrival: string }>
        inbound: Array<{ airline: string; flight: string; departure: string; arrival: string }>
    }
    hotels?: Array<{
        name: string
        address: string
        checkIn: string
        checkOut: string
    }>
}

// 進度回調類型
export type ProgressCallback = (current: number, total: number, stage: string) => void

// 分類圖示對應
const CATEGORY_ICONS: Record<string, string> = {
    sightseeing: "🏛️",
    food: "🍜",
    transport: "🚃",
    shopping: "🛍️",
    hotel: "🏨",
    activity: "🎯",
    other: "📍"
}

// A4 尺寸常數
const PAGE_WIDTH = 794  // px (A4 at 96 DPI)
const PAGE_STYLE = `
    width: ${PAGE_WIDTH}px;
    min-height: 1123px;
    background-color: #ffffff;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans TC', 'Microsoft JhengHei', sans-serif;
    padding: 40px;
    box-sizing: border-box;
    color: #1e293b;
`

/**
 * 防止 XSS 的 HTML 轉義
 */
function escapeHtml(text: string): string {
    if (!text) return ''
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;')
}

/**
 * 🆕 建立封面頁容器
 */
function createCoverContainer(data: TripPDFData): HTMLDivElement {
    const container = document.createElement("div")
    container.style.cssText = PAGE_STYLE + `
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        text-align: center;
    `

    container.innerHTML = `
        <h1 style="font-size: 36px; font-weight: bold; color: #1e293b; margin-bottom: 24px;">
            ${escapeHtml(data.title)}
        </h1>
        <p style="font-size: 18px; color: #64748b; margin-bottom: 40px;">
            ${escapeHtml(data.startDate)} - ${escapeHtml(data.endDate)}
        </p>
        ${data.coverImage ? `<img src="${data.coverImage}" style="max-width: 80%; max-height: 400px; object-fit: cover; border-radius: 12px; margin-bottom: 40px;" />` : ''}
        <p style="font-size: 14px; color: #94a3b8; margin-top: auto; padding-top: 60px;">
            Generated by Tabidachi | ${new Date().toLocaleDateString()}
        </p>
    `
    return container
}

/**
 * 🆕 建立單天頁面容器
 */
function createDayContainer(dayData: TripPDFData['days'][0]): HTMLDivElement {
    const container = document.createElement("div")
    container.style.cssText = PAGE_STYLE

    const activities = (dayData.activities || []).map(act => `
        <div style="background-color: #f8fafc; padding: 14px; border-radius: 6px; border-left: 4px solid #3b82f6; margin-bottom: 10px;">
            <div style="font-weight: bold; font-size: 15px; color: #1e293b;">
                ${escapeHtml(act.time)} ${CATEGORY_ICONS[act.category] || '📍'} ${escapeHtml(act.place)}
            </div>
            ${act.desc ? `<div style="font-size: 13px; color: #64748b; margin-top: 6px; padding-left: 10px;">${escapeHtml(act.desc)}</div>` : ''}
            ${act.memo ? `<div style="font-size: 12px; color: #b45309; margin-top: 6px; padding-left: 10px; font-style: italic;">💡 ${escapeHtml(act.memo)}</div>` : ''}
        </div>
    `).join('')

    const notes = dayData.notes && dayData.notes.length > 0 ? `
        <div style="margin-top: 24px; background-color: #fffbeb; padding: 16px; border-radius: 8px;">
            <h3 style="font-size: 16px; font-weight: bold; margin-bottom: 12px; color: #92400e;">📝 筆記</h3>
            ${dayData.notes.map(note => `
                <div style="font-size: 13px; margin-bottom: 8px; color: #78350f;">
                    • <strong>${escapeHtml(note.title)}:</strong> ${escapeHtml(note.content)}
                </div>
            `).join('')}
        </div>
    ` : ''

    container.innerHTML = `
        <h2 style="font-size: 24px; font-weight: bold; color: #1e293b; border-bottom: 3px solid #3b82f6; padding-bottom: 12px; margin-bottom: 20px;">
            Day ${dayData.day} - ${escapeHtml(dayData.date)}
        </h2>
        ${dayData.location ? `<p style="font-size: 15px; color: #64748b; margin-bottom: 20px;">📍 ${escapeHtml(dayData.location)}</p>` : ''}
        ${activities.length > 0 ? activities : '<p style="color: #94a3b8; font-style: italic;">無安排活動</p>'}
        ${notes}
    `
    return container
}

/**
 * 🆕 建立住宿頁面容器
 */
function createHotelsContainer(hotels: TripPDFData['hotels']): HTMLDivElement | null {
    if (!hotels || hotels.length === 0) return null

    const container = document.createElement("div")
    container.style.cssText = PAGE_STYLE

    container.innerHTML = `
        <h2 style="font-size: 24px; font-weight: bold; color: #1e293b; border-bottom: 3px solid #10b981; padding-bottom: 12px; margin-bottom: 24px;">
            🏨 住宿資訊
        </h2>
        ${hotels.map(hotel => `
            <div style="background-color: #f0fdf4; padding: 16px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid #10b981;">
                <div style="font-weight: bold; font-size: 16px; color: #166534; margin-bottom: 6px;">${escapeHtml(hotel.name)}</div>
                <div style="font-size: 14px; color: #15803d;">${escapeHtml(hotel.checkIn || '')} - ${escapeHtml(hotel.checkOut || '')}</div>
                ${hotel.address ? `<div style="font-size: 13px; color: #64748b; margin-top: 4px;">${escapeHtml(hotel.address)}</div>` : ''}
            </div>
        `).join('')}
    `
    return container
}

/**
 * 🆕 將 HTML 容器渲染為 Canvas
 */
async function renderToCanvas(element: HTMLDivElement): Promise<HTMLCanvasElement> {
    element.style.position = 'absolute'
    element.style.left = '-9999px'
    element.style.top = '0'
    document.body.appendChild(element)

    try {
        const canvas = await html2canvas(element, {
            scale: 1.5,  // 🆕 降低 scale 提升效能
            useCORS: true,
            allowTaint: true,
            backgroundColor: "#ffffff",
            logging: false
        })
        return canvas
    } finally {
        document.body.removeChild(element)
    }
}

/**
 * 🆕 生成行程 PDF（每天獨立渲染，避免崩潰和切割）
 * @param data 行程資料
 * @param onProgress 進度回調
 * @returns PDF blob URL
 */
export async function generateTripPDF(
    data: TripPDFData,
    onProgress?: ProgressCallback
): Promise<string> {
    // 空行程檢查
    if (!data.days || data.days.length === 0) {
        throw new Error("行程內容為空，無法生成 PDF。")
    }

    const pdf = new jsPDF("p", "mm", "a4")
    const imgWidth = 210  // A4 寬度 mm
    const imgHeight = 297 // A4 高度 mm
    const totalPages = 1 + data.days.length + (data.hotels?.length ? 1 : 0)
    let currentPage = 0
    let isFirstPage = true

    // 1. 封面頁
    onProgress?.(++currentPage, totalPages, "生成封面...")
    const coverContainer = createCoverContainer(data)
    const coverCanvas = await renderToCanvas(coverContainer)
    const coverHeight = (coverCanvas.height * imgWidth) / coverCanvas.width
    pdf.addImage(coverCanvas.toDataURL("image/jpeg", 0.9), "JPEG", 0, 0, imgWidth, Math.min(coverHeight, imgHeight))
    isFirstPage = false

    // 2. 每天獨立一頁（🆕 核心優化）
    for (const dayData of data.days) {
        onProgress?.(++currentPage, totalPages, `生成 Day ${dayData.day}...`)

        if (!isFirstPage) pdf.addPage()

        const dayContainer = createDayContainer(dayData)
        const dayCanvas = await renderToCanvas(dayContainer)
        const dayHeight = (dayCanvas.height * imgWidth) / dayCanvas.width

        // 如果內容超過一頁，縮放填滿
        pdf.addImage(dayCanvas.toDataURL("image/jpeg", 0.9), "JPEG", 0, 0, imgWidth, Math.min(dayHeight, imgHeight))
        isFirstPage = false
    }

    // 3. 住宿頁
    const hotelsContainer = createHotelsContainer(data.hotels)
    if (hotelsContainer) {
        onProgress?.(++currentPage, totalPages, "生成住宿資訊...")
        pdf.addPage()
        const hotelsCanvas = await renderToCanvas(hotelsContainer)
        const hotelsHeight = (hotelsCanvas.height * imgWidth) / hotelsCanvas.width
        pdf.addImage(hotelsCanvas.toDataURL("image/jpeg", 0.9), "JPEG", 0, 0, imgWidth, Math.min(hotelsHeight, imgHeight))
    }

    onProgress?.(totalPages, totalPages, "完成！")

    // 輸出 Blob URL
    const blob = pdf.output("blob")
    return URL.createObjectURL(blob)
}

/**
 * 下載 PDF
 */
export function downloadPDF(blobUrl: string, filename: string) {
    const link = document.createElement("a")
    link.href = blobUrl
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)

    // 清理 blob URL
    setTimeout(() => URL.revokeObjectURL(blobUrl), 1000)
}
